### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Hussein-L-AlMadhachi** [redraiment/basic#1]
First of all , I highly admire the minimalism in this code and the low memory usage which makes this project amazing, it's really rare to find such projects these days

Unfortunately, your project doesn't have a specified license that explain whether this code may or may not be used for other free and open source projects and what are the limitation of using, copying, and modifying the source code

I hope this problem get fixed to avoid confusion

and honestly thank you for this wonderful peace of art

**Comment by redraiment** [comment]
Thanks for your suggestion!

This is a project I created for for educational purposes in 2009, so it's not a rigorous project, and no enough comments and documents.
Anyway, to keep the source code available for study and research, the project has been licensed under the MIT license.
Therefore, feel free to use the source code in your way, :-)
